### PR TITLE
Add Wayland configuration

### PR DESCRIPTION
**Pull request by Tooniis**
Add configration to enable the VK_USE_PLATFORM_WAYLAND_KHR version.

### CODE REVIEW

**Comment by SKY-13th** [comment]
Hi, 

As far as I know, package `versions` in dub are bypassed to all dependencies. 
There should be no need to add them as separate configurations explicitly.

This should be good to go:
```
{
    "name": "myproject",
    "versions": ["VK_USE_PLATFORM_WAYLAND_KHR"],
    "dependencies": {
        "derelict-vulkan": "~>0.0.20"
    }
}
```

**Comment by Tooniis** [comment]
I added configurations to leave `VK_KHR_wayland_surface` support optional. Otherwise I think I should just remove the version all together.

**Comment by SKY-13th** [comment]
Sorry, I think I'm missing something.

What is the point in adding configuration, to leave it optional?
As it's already an option under the version condition.
At least I see it as an optional functionality.

If to look at other binding for the example, it looks like some of them treat it the same way.
For example [bindbc-sdl](https://github.com/BindBC/bindbc-sdl):
Modules for `SDL_Image`/etc are under version conditions.
Only things that are moved under configurations are binding types, which are require change in dependencies and compiler flags.

**Comment by Tooniis** [comment]
I'm not using dub for my project, and instead building this library separately and installing it to system paths in an Arch package (https://aur.archlinux.org/packages/derelict-vulkan/).

**Comment by SKY-13th** [comment]
OK

I see why you may not want to use dub. 
But it's not clear why would you use AUR for it instead. And why package should be built for Wayland only.
As a direct dependency for a project it make sense, but as an AUR pkg - no.

Why this change need to be integrated into the main dub package?
May you setup AUR package build script, to setup local "proxy" dub project to build library with required version flags?
(I'm not familiar with how AUR packages are built)
Can you use your fork of the package for it?
Or fetch it locally, as part of your project setup, and patch for you needs?

Sorry, may be it's too much, but it just made me curious.

I had, in a way, similar kind of issue with C/C++ dependencies with my D project.  I end up using Conan, for it. 
It allowed me to have both, remote recipes from global server, and local ones for specials cases, with local patches, etc.

**Comment by Tooniis** [comment]
>  But it's not clear why would you use AUR for it instead. And why package should be built for Wayland only.
> As a direct dependency for a project it make sense, but as an AUR pkg - no.

True. ideally all features would be enabled for a package so that it fulfills the needs of everyone.

> Why this change need to be integrated into the main dub package?

It doesn't *need* to, but I thought it would be better to merge it upstream instead of carrying a patch locally or in the Arch package. Someone else might also need this in the future. 

> Or fetch it locally, as part of your project setup, and patch for you needs?

I might end up just doing this, maybe with git submodules. I generally prefer to use libraries from system paths instead of integrating them into the project, but I see how it might make sense for bindings.

**Comment by SKY-13th** [comment]
OK, thanks, that cleared everything up.

Through, I don't think that anyone will have a use out of it.
Package is here, probably, more for a legacy reasons. In case if anyone still using it.
Probably everyone interested in using Vulkan in D are switched to [erupted](https://github.com/ParticlePeter/ErupteD).
May advise you to take a look at it too. It's a lot more up to date.

**Comment by Tooniis** [comment]
I've tried to use erupted before this, but I had some issues building it. It seems that it is based on an older version of vulkan-docs. I tried updating it but I still had some other issues when I tried to use it. I'll give it another try. Thanks.

Closing this for now.

**Pull request closed without merging**
